"""i25_fold_v4.py -- FOLD-V4: the DE-OOD belief encoder (per DESIGN_SHEET_FOLD_V4_DEOOD.md).

THE BUG (v3.1): interviews were sampled with on_profile=0.7 (privileged -- the interviewer is assumed
to already know the user's taste region). At deployment the blind/adaptive policies land OFF-profile,
so the fold is OOD: elicitation barely lifts (+0.02) and the expected-gain order collapses (-0.006).

THE FIX (author-designed, single fixed length B=8): retrain the SAME FoldV31 architecture on interviews
generated by an ENSEMBLE of REAL selection strategies run through the REAL gated v2.1 answerer (the
arena world: fitted v2.1 knowledge/value models + EASE backbone + 2,428-question universe). Answers are
NEVER faked -- only SELECTION is randomized broadly, biased toward the HARD TAILS (off-profile / niche /
famous-refusal) where the fold currently collapses. Plus ~30% clean full profiles to keep real-profile
skill. One selection strategy (POPULARITY) + blind-EIG are HELD OUT entirely for the generalization gate.

Generation is done IN THE ARENA WORLD (arena_core.Arena) so the fold trains on the ACTUAL deployment
distribution -- this simultaneously removes the sampler-vs-arena distribution shift v3.1 carried.

NO LLM calls. $0. Firewall: population trU users only (the 173/300 study/eval users NEVER touched);
fold training uses users [0:5000] of the seed-123 shuffle = strictly inside the arena TRAIN range,
DISJOINT from the seed-123 DEVTEST split [17000:20000] the baselines are scored on. Deterministic.

Run:
  python scripts/i25_fold_v4.py train --n_train 4000 --n_val 1000 --epochs 10
  python scripts/i25_fold_v4.py smoke
"""
import os
os.environ.setdefault("OMP_NUM_THREADS", "4")
os.environ.setdefault("MKL_NUM_THREADS", "4")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "4")
import sys, json, time, argparse
import numpy as np
import torch
torch.set_num_threads(4)

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE); sys.path.insert(0, os.path.join(_HERE, "instrument2"))
import warnings
warnings.filterwarnings("ignore")

import arena_core as AC
import i25_fold_v31 as FV31
import i25_lib as L
from i25_fold_v3_sampler import (TYPE_ITEM, KIND_IMPL, KIND_EXPL, LVL_ROUGH, LVL_KW, FID_DATA)

BEST = ".cache/i25_fold_v4_best.pt"
CKPT = ".cache/i25_fold_v4.pt"
LOGP = ".cache/i25_fold_v4_log.json"
RESULTS = ".cache/arena/fold_v4_results.json"
CLEAN_FRAC = 0.30
BFIX = 8
MAX_CLEAN_ITEMS = 60
K = 10                                  # arena PRIMARY endpoint metric

# SHARED-MIXTURE encoder over ALL real selection arms (answers via the real answerer; only SELECTION
# is randomized). blind-EIG (info-gain) is HELD OUT entirely for the generalization gate -- it is the
# deployed adaptive policy that COLLAPSED (-0.006) under the OOD v3.1 fold, so a clean held-out test.
STRAT_W = {"random": 0.14, "popularity": 0.10, "entropy": 0.10, "on_profile": 0.14,
           "off_niche": 0.24, "adversarial": 0.18, "mixed": 0.10}   # fat tails: niche+adversarial=0.42
SEEN = list(STRAT_W.keys())
HELDOUT = ["blind_eig"]                  # never trained; probed in G-generalize + Task-3 rerun


def _sanitize_qemb(ar):
    """A handful of degenerate region bags yield non-finite embeddings (e.g. concept q718). Zero them
    so their tokens are harmless no-info tokens instead of poisoning the batch with NaN."""
    bad = ~np.isfinite(ar.Qemb).all(1)
    nb = int(bad.sum())
    if nb:
        ar.Qemb[bad] = 0.0
        for qi in np.where(bad)[0]:
            ar._emb_cache[int(qi)] = ar.Qemb[int(qi)]
        ar.Qemb_norm = np.linalg.norm(ar.Qemb, axis=1) + 1e-9
        print(f"[sanitize] zeroed {nb} non-finite q-embedding row(s): {list(np.where(bad)[0])}",
              flush=True)


# ============================================================ the de-OOD interview generator
class DeOODGen:
    """Ensemble selection over the arena's 2,428-question universe. Static orders (pop/niche/entropy)
    precomputed once; on/off-profile decided per-user by revealed-member overlap n_E (privileged
    SELECTION is legal -- answers come from the real answerer regardless)."""

    def __init__(self, ar, train_sub, verbose=True):
        self.ar = ar
        self.pop_order = np.argsort(-ar.q_popmass)                 # famous first
        self.niche_order = np.argsort(ar.q_popmass)                # obscure first
        # rating-entropy order over a TRAIN subsample (classic Rashid/Golbandi; fold-independent)
        Vtab = np.stack([ar.user_table(r["u"], r["known"])["val"] for r in train_sub])
        ent = np.zeros(ar.nQ)
        for q in range(ar.nQ):
            vq = Vtab[:, q]; vq = vq[vq >= 0].astype(int)
            if vq.size >= 2:
                c = np.bincount(vq, minlength=4).astype(float); pr = c[c > 0] / c.sum()
                ent[q] = float(-(pr * np.log2(pr)).sum())
        self.ent_order = np.argsort(-ent)
        self.ent_top = [int(q) for q in self.ent_order[:400]]
        self.niche_top = [int(q) for q in self.niche_order[:1500]]
        self.fam_top = [int(q) for q in self.pop_order[:800]]
        # HELD-OUT blind-EIG order (fold-derived) -- reuse cached v3.1 prescreen if present (same
        # seed-123 train-sub users), else compute on the current (v3.1) fold. Eval-only.
        self.eig_top = self._eig_order(ar, train_sub)
        if verbose:
            print(f"[gen] static orders ready (pop/niche/entropy over {len(train_sub)} train-sub); "
                  f"strategies SEEN={SEEN} HELD-OUT={HELDOUT}", flush=True)

    def _eig_order(self, ar, train_sub):
        cached = ".cache/arena/pres31_baselines_v2_n800_K10.json"
        try:
            if os.path.exists(cached):
                g = np.array(json.load(open(cached))["gain"])
                if len(g) == ar.nQ:
                    return [int(q) for q in np.argsort(-g)[:400]]
        except Exception:
            pass
        import arena_policies as AP
        g = AP.prescreen_gains(ar, train_sub, K=K, tag="v4gen_eig", verbose=False)
        return [int(q) for q in np.argsort(-g)[:400]]

    def _nE(self, known):
        u = self.ar.uni
        ind = np.zeros(u.ni, np.float64)
        for j in known:
            jj = int(j)
            if 0 <= jj < u.ni:
                ind[jj] = 1.0
        return np.concatenate([np.asarray(u.tagM.dot(ind)).ravel(),
                               np.asarray(u.entM.dot(ind)).ravel(), ind[u.bank]])

    def select(self, r, strat, rng, B=BFIX):
        nQ = self.ar.nQ
        nE = self._nE(r["known"])
        on_pool = [int(q) for q in np.argsort(-nE) if nE[q] > 0]
        onset = set(on_pool)

        def _fill(qs):
            if len(qs) >= B:
                return qs[:B]
            have = set(qs)
            pool = [int(q) for q in rng.choice(nQ, size=min(nQ, B * 4), replace=False)
                    if int(q) not in have]
            return (qs + pool)[:B]

        if strat == "random":
            return [int(q) for q in rng.choice(nQ, size=B, replace=False)]
        if strat == "popularity":
            return [int(q) for q in self.pop_order[:B]]
        if strat == "entropy":
            return list(self.ent_top[:B])
        if strat == "blind_eig":                                   # HELD OUT (eval only)
            return list(self.eig_top[:B])
        if strat == "on_profile":
            return _fill(list(on_pool[:B]))
        if strat == "off_niche":                                   # obscure & off-profile -> refusals
            return _fill([q for q in self.niche_top if q not in onset][:B])
        if strat == "adversarial":                                 # famous but off-profile -> expected-refusal
            return _fill([q for q in self.fam_top if q not in onset][:B])
        if strat == "mixed":                                       # explore early -> exploit late
            early = [q for q in self.niche_top if q not in onset][:B // 2]
            late = on_pool[:B - len(early)]
            return _fill(early + late)
        raise ValueError(strat)

    # ---- tokens for an interview (real answerer) ----
    def interview_tokens(self, r, qs):
        ar = self.ar; ctx = ar.user_ctx(r); uid = r["u"]
        toks, nat = [], []
        for qi in qs:
            toks += ar.tokens_for(uid, qi, ctx)
            if ar.answered(uid, qi, ctx) and ar.is_liked_item(uid, qi, ctx):
                nat.append(int(ar.uni.bank[qi - ar.off_item]))
        return toks, nat

    # ---- tokens for a clean full profile ----
    def clean_tokens(self, r, rng):
        ar = self.ar; known = r["known"]
        ks = list(known.keys())
        if len(ks) > MAX_CLEAN_ITEMS:
            ks = [ks[i] for i in rng.choice(len(ks), size=MAX_CLEAN_ITEMS, replace=False)]
        mu = float(np.mean([known[j] for j in known]))
        toks, nat = [], []
        for j in ks:
            j = int(j)
            if not (0 <= j < ar.FR.Wn.shape[0]):
                continue
            emb = ar.FR.Wn[j].numpy().astype(np.float32)
            toks.append((TYPE_ITEM, KIND_IMPL, LVL_KW, 0.0, FID_DATA, 0.0, emb, 0.0))
            toks.append((TYPE_ITEM, KIND_EXPL, LVL_ROUGH, 0.0, FID_DATA, float(known[j] - mu), emb, 0.0))
            if known[j] >= 4:
                nat.append(j)
        return toks, nat

    def build_reveal(self, r, rng, clean_frac=CLEAN_FRAC):
        if rng.random() < clean_frac:
            return self.clean_tokens(r, rng)
        strat = rng.choice(SEEN, p=[STRAT_W[s] for s in SEEN])
        return self.interview_tokens(r, self.select(r, strat, rng))


# ============================================================ loss / val (reuse FoldV31 packing)
def batch_loss(FR, model, gen, users, rng):
    tl, nl, tgt, prof = [], [], [], []
    for u in users:
        toks, nat = gen.build_reveal(u, rng)
        if not toks:
            continue
        tl.append(toks); nl.append(nat); tgt.append(u["held"]); prof.append(set(u["known"].keys()))
    if not tl:
        return None
    tt, tk, tll, ts, ta, tf, tv, te, mask, nz = FV31.pack_batch(FR, tl, nl)
    z = model(tt, tk, tll, ts, ta, tf, tv, te, mask, nz)
    Smat = z @ FR.W.T + FR.bdec
    B, ni = Smat.shape
    negmask = torch.zeros((B, ni), dtype=torch.bool)
    tg = torch.zeros((B, ni), dtype=torch.float32)
    for b in range(B):
        negmask[b, list(prof[b])] = True
        tg[b, list(tgt[b])] = 1.0
    Smat = Smat.masked_fill(negmask, -1e9)
    logp = torch.log_softmax(Smat, dim=1)
    n_t = tg.sum(1).clamp(min=1)
    return -((logp * tg).sum(1) / n_t).mean()


def _fold_ndcg(ar, model, tok_lists, nat_lists, held, prof, kk=K):
    vals = []
    for s in range(0, len(tok_lists), 1200):
        e = min(s + 1200, len(tok_lists))
        Z = FV31.fold_batch(ar.FR, model, tok_lists[s:e], nat_lists[s:e])
        vv = AC.ndcg_at_k_batch(ar.FR, Z, held[s:e], prof[s:e], kk)
        vals += [v for v in vv if v is not None]
    return float(np.mean(vals)) if vals else 0.0


@torch.no_grad()
def val_ndcg(ar, model, gen, val_users, seed):
    """Deterministic val: fixed 30% clean + rotated SEEN strategies at B=8 (the deployment length)."""
    model.eval()
    rng = np.random.default_rng(seed)
    tl, nl, held, prof = [], [], [], []
    for i, u in enumerate(val_users):
        if rng.random() < CLEAN_FRAC:
            toks, nat = gen.clean_tokens(u, rng)
        else:
            strat = SEEN[i % len(SEEN)]
            toks, nat = gen.interview_tokens(u, gen.select(u, strat, rng))
        if toks:
            tl.append(toks); nl.append(nat); held.append(u["held"]); prof.append(set(u["known"].keys()))
    return _fold_ndcg(ar, model, tl, nl, held, prof)


# ============================================================ gates
@torch.no_grad()
def gate_clean(ar, model, val_users):
    """G-clean: clean full-profile fold >= native RecVAE."""
    rng = np.random.default_rng(41)
    tl, nl, held, prof = [], [], [], []
    natez = []
    for u in val_users:
        toks, nat = ar.gen.clean_tokens(u, rng)
        tl.append(toks); nl.append(nat); held.append(u["held"]); prof.append(set(u["known"].keys()))
        natez.append(list(u["known"].keys()))
    fold = _fold_ndcg(ar, model, tl, nl, held, prof)
    # native RecVAE
    vals = []
    for s in range(0, len(natez), 1200):
        e = min(s + 1200, len(natez))
        Zn = ar.FR.enc_items(natez[s:e]).numpy().astype(np.float64)
        vv = AC.ndcg_at_k_batch(ar.FR, Zn, held[s:e], prof[s:e], K)
        vals += [v for v in vv if v is not None]
    nat = float(np.mean(vals)) if vals else 0.0
    passed = bool(fold >= nat - 0.01)
    return dict(fold_ndcg=fold, native_ndcg=nat, gap=fold - nat, n=len(tl), **{"pass": passed})


@torch.no_grad()
def gate_generalize(ar, model, val_users, cold0):
    """G-generalize: fold NDCG@8 on the HELD-OUT blind-EIG strategy (never trained) within tolerance
    of the SEEN strategies. Also reports each strategy's endpoint@8 lift over cold."""
    gen = ar.gen
    strat_list = SEEN + ["blind_eig"]
    out = {}
    for strat in strat_list:
        rng = np.random.default_rng(abs(hash(strat)) % (2 ** 31))
        tl, nl, held, prof = [], [], [], []
        for u in val_users:
            toks, nat = gen.interview_tokens(u, gen.select(u, strat, rng))
            if toks:
                tl.append(toks); nl.append(nat); held.append(u["held"]); prof.append(set(u["known"].keys()))
        nd = _fold_ndcg(ar, model, tl, nl, held, prof)
        out[strat] = dict(ndcg8=nd, lift=nd - cold0)
    seen_nd = [out[s]["ndcg8"] for s in SEEN]
    mean_seen = float(np.mean(seen_nd)); min_seen = float(np.min(seen_nd))
    eig_nd = out["blind_eig"]["ndcg8"]
    passed = bool(eig_nd >= mean_seen - 0.02)
    return dict(per_strategy=out, mean_seen_ndcg8=mean_seen, min_seen_ndcg8=min_seen,
                heldout_blind_eig_ndcg8=eig_nd, tol=0.02, **{"pass": passed})


# ============================================================ train
def cmd_train(args):
    t0 = time.time()
    print("[v4] building arena (gated v2.1 world + EASE + 2,428-q universe) ...", flush=True)
    ar = AC.Arena()
    _sanitize_qemb(ar)
    # cohorts: train [0:n_train], val [n_train:n_train+n_val] -- both inside arena TRAIN range,
    # DISJOINT from seed-123 devtest [17000:20000] used by the baselines.
    coh = AC.make_cohorts(ar, n_train=args.n_train, n_devval=args.n_val, n_devtest=100)
    tr_users, val_users = coh["train"], coh["devval"]
    train_sub = tr_users[:min(800, len(tr_users))]
    print(f"[v4] cohorts: train {len(tr_users)} / val {len(val_users)} (seed {AC.SEED}); "
          f"generating answer tables (real gated v2.1 answerer) ...", flush=True)
    # prefill answer tables (the expensive gated generation; cached to disk by cohort cfg)
    ar.prefill_answers(tr_users, "v4train", dict(role="v4train", n=args.n_train))
    ar.prefill_answers(val_users, "v4val", dict(role="v4val", n=args.n_val))
    print(f"[v4] answer tables ready [{(time.time()-t0)/60:.1f}m]", flush=True)

    gen = DeOODGen(ar, train_sub)
    ar.gen = gen
    cold0 = _fold_ndcg(ar, ar.model, [[]] * len(val_users), [[]] * len(val_users),
                       [u["held"] for u in val_users], [set(u["known"].keys()) for u in val_users])
    print(f"[v4] val COLD NDCG@10 (v3.1 fold, ask-nothing) = {cold0:.4f}", flush=True)

    torch.manual_seed(args.seed); np.random.seed(args.seed)
    model = FV31.FoldV31()
    opt = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=1e-6)
    step_rng = np.random.default_rng(args.seed + 4040)
    state = dict(epoch=0, best_val=-1.0, best_epoch=-1, history=[], strategies_seen=SEEN,
                 strategies_heldout=HELDOUT, clean_frac=CLEAN_FRAC, cold0=cold0)
    print(f"[v4] === training FoldV31 (de-OOD, B={BFIX}, {int(CLEAN_FRAC*100)}% clean), "
          f"epochs={args.epochs} ===", flush=True)
    for ep in range(args.epochs):
        model.train()
        order = np.arange(len(tr_users)); step_rng.shuffle(order)
        tot, nb = 0.0, 0
        for b0 in range(0, len(order), args.batch):
            us = [tr_users[i] for i in order[b0:b0 + args.batch]]
            loss = batch_loss(ar.FR, model, gen, us, step_rng)
            if loss is None or not torch.isfinite(loss):
                continue                                            # never poison weights with NaN/inf
            opt.zero_grad(); loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 5.0)
            opt.step()
            tot += float(loss.item()); nb += 1
        vN = val_ndcg(ar, model, gen, val_users, args.seed + 7)
        state["epoch"] = ep + 1
        rec = dict(epoch=ep + 1, train_loss=round(tot / max(nb, 1), 4), val_ndcg=round(vN, 4),
                   min=round((time.time() - t0) / 60, 1))
        state["history"].append(rec)
        print(f"[v4] ep {ep+1:2d} | loss {rec['train_loss']:.4f} | val NDCG@10 {vN:.4f} | "
              f"{rec['min']}m", flush=True)
        torch.save(dict(model=model.state_dict(), opt=opt.state_dict(), state=state,
                        args=vars(args)), CKPT)
        if vN > state["best_val"]:
            state["best_val"] = vN; state["best_epoch"] = ep + 1
            torch.save(dict(model=model.state_dict(), state=state, args=vars(args)), BEST)
        json.dump(state["history"], open(LOGP, "w"), indent=1)
    print(f"[v4] BEST val {state['best_val']:.4f} @ep{state['best_epoch']} -> {BEST} "
          f"[{(time.time()-t0)/60:.1f}m]", flush=True)

    # ---- gates on the BEST checkpoint ----
    print("\n=== PRE-REGISTERED GATES (printed before results) ===", flush=True)
    print("  G-clean:      clean full-profile fold NDCG@10 >= native RecVAE - 0.01.", flush=True)
    print("  G-generalize: HELD-OUT blind-EIG NDCG@8 >= mean(SEEN strategies NDCG@8) - 0.02.", flush=True)
    blob = torch.load(BEST, map_location="cpu")
    best = FV31.FoldV31(); best.load_state_dict(blob["model"]); best.eval()
    gc = gate_clean(ar, best, val_users)
    gg = gate_generalize(ar, best, val_users, cold0)
    print(f"\n[G-clean]      fold {gc['fold_ndcg']:.4f}  native {gc['native_ndcg']:.4f}  "
          f"gap {gc['gap']:+.4f}  -> {'PASS' if gc['pass'] else 'FAIL'}", flush=True)
    print("[G-generalize] NDCG@8 by strategy (SEEN | held-out):", flush=True)
    for s in SEEN:
        d = gg["per_strategy"][s]
        print(f"    {s:12s} {d['ndcg8']:.4f}  lift {d['lift']:+.4f}", flush=True)
    d = gg["per_strategy"]["blind_eig"]
    print(f"    {'blind_eig':12s} {d['ndcg8']:.4f}  lift {d['lift']:+.4f}  (HELD OUT)", flush=True)
    print(f"    mean(seen)={gg['mean_seen_ndcg8']:.4f}  held-out blind-EIG="
          f"{gg['heldout_blind_eig_ndcg8']:.4f}  -> {'PASS' if gg['pass'] else 'FAIL'}", flush=True)

    R = {}
    if os.path.exists(RESULTS):
        try:
            R = json.load(open(RESULTS))
        except Exception:
            R = {}
    R["fold_v4"] = dict(best_val=state["best_val"], best_epoch=state["best_epoch"],
                        cold0=cold0, history=state["history"], n_train=len(tr_users),
                        n_val=len(val_users), strategies_seen=SEEN, strategies_heldout=HELDOUT,
                        clean_frac=CLEAN_FRAC, B=BFIX, ckpt=BEST)
    R["gates"] = dict(G_clean=gc, G_generalize=gg)
    os.makedirs(os.path.dirname(RESULTS), exist_ok=True)
    json.dump(R, open(RESULTS, "w"), indent=1, default=float)
    print(f"\n[v4] wrote fold val + gates -> {RESULTS} [{(time.time()-t0)/60:.1f}m]", flush=True)
    return R


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["train", "smoke"])
    ap.add_argument("--n_train", type=int, default=4000)
    ap.add_argument("--n_val", type=int, default=1000)
    ap.add_argument("--epochs", type=int, default=10)
    ap.add_argument("--batch", type=int, default=256)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--seed", type=int, default=0)
    a = ap.parse_args()
    if a.cmd == "smoke":
        a.n_train = 80; a.n_val = 60; a.epochs = 1
    cmd_train(a)
